### PR TITLE
Added a method for most efficient to concatenate many strings.

### PR DESCRIPTION
**Pull request by RodolfoSilva**
See: https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together

https://wiki.python.org/moin/ConcatenationTestCode

### CODE REVIEW

**Comment by jehna** [comment]
Good addition. I'd raise one potential issue with converting `*args` at `add` method to a list: It could potentially raise issues if someone wants to add optional arguments to it later on?

So what I'd suggest is that we'd keep `add` method working with string input, but add the string input itself to the list:
```
add(self, value):
    self.s.append(value)
    return self
```

And, if there's string concatenation needed (like in the `any` method), we'd build the string with e.g. the `%` method:

```
def any(self, value):
      return self.add("([%s])" % value)
      any_of = any
```

With a quick testing it also seems that this method is quite a bit faster. I tested this with the following script:
```
import timeit
print "List: %f" % timeit.timeit('value = "test"\ns = []\ndef add(*args):\n  s.extend(list(args))\nfor i in range(0,100000): add("([",value,"])")', number=500)
print "Percent: %f" % timeit.timeit('value = "test"\ns = []\ndef add(value):\n  s.append(value)\nfor i in range(0,100000): add("([%s])" % value)', number=500)
```
Which outputs (on my mac):
```
List: 21.318564
Percent: 13.609931
```
Please correct me if I made any mistakes with the test :)

**Comment by jehna** [comment]
Hmm. Just out of curiosity I also timed the `+` method and directly calling `"".join`:

```
import timeit
print "List: %f" % timeit.timeit('value = "test"\ns = []\ndef add(*args):\n  s.extend(list(args))\nfor i in range(0,100000): add("([",value,"])")', number=500)
print "Percent: %f" % timeit.timeit('value = "test"\ns = []\ndef add(value):\n  s.append(value)\nfor i in range(0,100000): add("([%s])" % value)', number=500)
print "Plus: %f" % timeit.timeit('value = "test"\ns = []\ndef add(value):\n  s.append(value)\nfor i in range(0,100000): add("([" + value + "])")', number=500)
print "Join list: %f" % timeit.timeit('value = "test"\ns = []\ndef add(value):\n  s.append(value)\nfor i in range(0,100000): add("".join("([",value,"])"))', number=500)
```
outputs:
```
List: 21.471968
Percent: 13.712804
Plus: 12.235351
Join list: 19.227355
```

So it seems that for simple string concatenations, the `+` is faster.
I believe this is, because the strings in my example are rather small (as they should be when passed to `add` method). And calling the `list.extend(list(args))` actually makes the situation worse than the initial code.

So I'd propose that we'd keep the `add` function like this:
```
add(self, value):
    self.s.append(value)
    return self
```

and when calling `add`, we just concatenate the strings with `+`:
```
def any(self, value):
      return self.add("([" + value + "])")
      any_of = any
```

**Comment by RodolfoSilva** [comment]
Good observation. I'm going to change that method.

What do you think about that solution?

```python
def add(self, value):
    if isinstance(value, list):
        self.s.extend(value)
    else:
        self.s.append(value)
    return self
```

```python
def any(self, value):
      return self.add("([%s])" % value)
```

**Comment by jehna** [comment]
@RodolfoSilva looks good, I'd say that solution would be the most readable :+1:

**Pull request merged**
