### PR TITLE
Added Python3 support

### PR DESCRIPTION
**Pull request by omalsa04**
Also includes mehmetkose's and rajatkhanduja's changes.

### CODE REVIEW

**Comment by akkatracker** [comment]
Yes please!

**Comment by jehna** [comment]
Where are we currently on the Python 3 adoption? I've understood that Python 2.7's sunset date was postponed to 2020.

Would it be considered as a bad practice to make a `Python3VerbalExpressions` fork, to support both of the platforms? What do you think?

**Comment by ionutvmi** [comment]
As long as it is supports both python 2 & 3 I don't see why we should have 2 repos.

**Comment by akkatracker** [comment]
@jehna I agree with @ionutvmi . As long as it supports both there is no need for two repos. 

If it starts breaking (which this version doesn't appear to do) then perhaps 2 repos are needed.

**Comment by jehna** [comment]
If these are not breaking changes to 2.x version, it's fine to merge them to the repo.

If possible, you could add to the readme.md a note about the compatibility.

**Comment by omalsa04** [comment]
Hi @jehna, this version has really minimal changes to make it work on both Python3 and Python2. I've just merged in the latest upstream changes and tested that everything still works for both Python2 and Python3. I have just tested with Python 2.7.11 and 3.5.1, previously I tested in multiple Python 3 versions (but I can't find a record of this).

Can someone else try out this branch and run:
```
python setup.py develop
python setup.py test
```

and

```
python3 setup.py develop
python3 setup.py test
```

**Comment by ionutvmi** [comment]
I will close and reopen to trigger the travis build.

**Comment by vtitor** [comment]
@omalsa04 Thanks for your pr, but I closed this pr, because python 3 support is already implemented.

**Pull request closed without merging**
